"""empty message

Revision ID: ad209ad0f5cd
Revises: 
Create Date: 2020-01-12 06:21:57.082727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad209ad0f5cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_ibfk_1', 'address', type_='foreignkey')
    op.drop_column('address', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('address_ibfk_1', 'address', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
